### ISSUE TITLE
Error: Error: Twilio API request failed 

### ISSUE THREAD

**Issue by larnsce** [seankross/twilio#2]
Following the instructions on the twilio website, I set up an account, got an SMS capable number and also tested it on twilio. It works for ingoing and outgoing messages. I have also verified my personal phone number.

In R, I have followed instructions of the `README.md` and used the TEST Credentials SID and AUTHTOKEN from the twilio website as described. 

Trying to use the `twilio::tw_send_message()` function, I get the following error message:

`Error: Twilio API request failed [400] The From phone number 41790873668 is not a valid, SMS-capable inbound phone number or short code for your account. <https://www.twilio.com/docs/errors/21606>`

R version 3.3.2 (2016-10-31)
RStudio version 1.0.136 
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X El Capitan 10.11.6

**Comment by seankross** [comment]
When using test credentials you can only test sending messages from +15005550006, which will not actually send a message. If you want to actually send a message you'll need to use your live account credentials. For more information about what you can do with your test credentials see https://www.twilio.com/docs/api/rest/test-credentials
